---
- name: Check linux server monitoring agent exists
   stat:
     path: /opt/site24x7/monagent
   register: installed

- name: Download Site24x7 agent from public URL
  get_url:
    url: "https://staticdownloads.site24x7.com/server/Site24x7_Linux_{{ site24x7_architecture }}bit.install"
    dest: "/opt/Site24x7_Linux_{{ site24x7_architecture }}bit.install"
    mode: 0750
  when: not installed.stat.exists

- name : Install Site24x7 agent in the server
  shell: /opt/Site24x7_Linux_{{ site24x7_architecture }}bit.install -i -key={{ site24x7_device_key }} -installer=ansible {{ site24x7_additional_args }}
  when: (site24x7_proxy == "NONE" and not installed.stat.exists)

- name : Install Site24x7 agent in the server w/ site24x7_proxy
  shell: /opt/Site24x7_Linux_{{ site24x7_architecture }}bit.install -i -key={{ site24x7_device_key }} -installer=ansible -proxy={{ site24x7_proxy }} {{ site24x7_additional_args }}
  when: (site24x7_proxy != "NONE" and not installed.stat.exists)

- service: name=site24x7monagent state=restarted
  when: not installed.stat.exists

- name: Deleting 64 bit install file
  file: 
    state: absent
    path: /opt/Site24x7_Linux_{{ site24x7_architecture }}bit.install
  when: not installed.stat.exists

