---
- name: Install Site24x7 server monitoring agent
  hosts: hostname          ##Change this value to select desired hosts
  remote_user: root
  
  vars:
     device_key: SITE24X7DEVICEKEY  ##Change this value to the device key obtained from your site24x7 portal
     proxy: NONE                ##Change this value to required proxy setting like user:password@proxyhost:proxyport

  tasks:
     - name: Check linux server monitoring agent exists
       stat:
         path: /opt/site24x7/monagent
       register: installed
     - name: Download 64 bit Site24x7 agent from public URL
       get_url:
         url: https://staticdownloads.site24x7.com/server/Site24x7_Linux_64bit.install
         dest: /opt/Site24x7_Linux_64bit.install
         mode: 0750
       when: ansible_machine == "x86_64" and not installed.stat.exists
     - name : Install 64 bit Site24x7 agent in the server
       shell: /opt/Site24x7_Linux_64bit.install -i -key={{ device_key }}
       when: (ansible_machine == "x86_64" and proxy == "NONE" and not installed.stat.exists)
     - name : Install 64 bit Site24x7 agent in the server
       shell: /opt/Site24x7_Linux_64bit.install -i -key={{ device_key }} -proxy={{ proxy }}
       when: (ansible_machine == "x86_64" and proxy != "NONE" and not installed.stat.exists)
     - service: name=site24x7monagent state=restarted
       when: ansible_machine == "x86_64" and not installed.stat.exists
     - name: Download 32 bit Site24x7 agent from public URL
       get_url:
         url: https://staticdownloads.site24x7.com/server/Site24x7_Linux_32bit.install
         dest: /opt/Site24x7_Linux_64bit.install 
         mode: 0750
       when: ansible_machine == "i386" and not installed.stat.exists
     - name : Install 32 bit Site24x7 agent in the server
       shell: /opt/Site24x7_Linux_32bit.install -i -key={{ device_key }}
       when: (ansible_machine == "i386" and proxy == "NONE" and not installed.stat.exists)
     - name : Install 32 bit Site24x7 agent in the server
       shell: /opt/Site24x7_Linux_32bit.install -i -key={{ device_key }} -proxy={{ proxy }}
       when: (ansible_machine == "i386" and proxy != "NONE" and not installed.stat.exists)
     - service: name=site24x7monagent state=restarted
       when: ansible_machine == "i386" and not installed.stat.exists
     - name: Deleting 64 bit install file
       file: 
         state: absent
         path: /opt/Site24x7_Linux_64bit.install
       when: ansible_machine == "x86_64" and not installed.stat.exists
     - name: Deleting 32 bit install file
       file: 
         state: absent
         path: /opt/Site24x7_Linux_32bit.install
       when: ansible_machine == "i386"
